### ISSUE TITLE
2019 ebook: Revisit graphics centering

### ISSUE THREAD

**Issue by j9t** [HTTPArchive/almanac.httparchive.org#1391] opened 2020-10-28 16:44 UTC
In the [2019 ebook](https://play.google.com/store/books/details?id=EAr5DwAAQBAJ&pcampaignid=books_web_aboutlink), at least on mobile (latest Android with latest Google Play Books), what seems to be desired to be centered isn’t really centered, probably because of some margin or padding.

![Screenshot_20201028-162133](https://user-images.githubusercontent.com/1700772/97468018-1c1c8100-1945-11eb-9fdb-26c514d116c6.png)

**Comment by bazzadp** [comment] 2020-10-28 17:48
I'm going to close this as a duplicate of #1390

**Closed by bazzadp** 2020-10-28 17:48 UTC
Labels: bug, development

**Comment by bazzadp** [comment] 2020-10-28 18:48
BTW if you flick from "Flowing Text" to "Original page images" then it does present better. Guess because it's a PDF and not an EPUB so doesn't properly reflow because of that.
