### ISSUE TITLE
Background and border of Text under statistics of Featured Chapter

### ISSUE THREAD

**Issue by bharatagsrwal** [HTTPArchive/almanac.httparchive.org#1808] opened 2020-12-19 16:17 UTC
![image](https://user-images.githubusercontent.com/43988371/102693695-74d01200-4242-11eb-94ce-e7b4c84a0bc5.png)

Background and border of Text under statistics of Featured Chapter, Not sure whether it is intended, I feel its kind of odd when all three are compared

**Comment by rviscomi** [comment] 2020-12-19 17:01
`dns-prefetch` and `preload` are code literals that are formatted differently to make them stand out against normal text. The formatting applies monospaced font, background, and border styles.

Does that address your concern? If so you can close the issue. Otherwise, could you elaborate on what you think the correct formatting should be?

**Comment by bazzadp** [comment] 2020-12-21 00:48
Agreed. This was intentionally added in #1718 and the featured quotes follow the same convention as other inline code. So working as intended.

**Comment by bazzadp** [comment] 2020-12-22 14:51
Closing this. Feel free to reopen if you have an alternative styling suggestion.

**Closed by bazzadp** 2020-12-22 14:51 UTC
