### ISSUE TITLE
Text overlapping and overflow of code in web_almanac_2020_en.pdf

### ISSUE THREAD

**Issue by bharatagsrwal** [HTTPArchive/almanac.httparchive.org#1725] opened 2020-12-10 05:53 UTC
I was going through pdf book and found a few things

![image](https://user-images.githubusercontent.com/43988371/101727072-c9a0b980-3ad9-11eb-8166-561751c877f0.png)
text is overlapping (page 33 of PDF and page 27 of the book)

![image](https://user-images.githubusercontent.com/43988371/101727119-e0dfa700-3ad9-11eb-9325-5e2ab5a92f2c.png)
code overflow (page 40 of PDF and page 34 of the book)

**Comment by bharatagsrwal** [comment] 2020-12-10 11:21
@bazzadp, one more thing 
![image](https://user-images.githubusercontent.com/43988371/101763593-ffa76300-3b04-11eb-8d68-c9e450becf9e.png)
![image](https://user-images.githubusercontent.com/43988371/101765810-dd631480-3b07-11eb-8d7c-78591f4dcbea.png)

this looks so odd, the problem is in both pdf as well as web

**Comment by bazzadp** [comment] 2020-12-10 11:26
This code display and we just added a darker background in #1718 so working as intended.

Maybe for `<th>` we can remove this background color? @lex111 any opinions here?

**Comment by bharatagsrwal** [comment] 2020-12-10 11:34
> This is in `code` display and we just added a darker background in #1718 (much like GitHub has in this comment!) so working as intended.
> 
> Maybe for `<th>, <td>` we can remove this background color? @lex111 any opinions here?

Not only `<th><tr>` we have do it for `<ul> and <li>` as the side navigation also have the same issue

![image](https://user-images.githubusercontent.com/43988371/101766696-2bc4e300-3b09-11eb-9ba5-48054a60c169.png)

**Comment by bharatagsrwal** [comment] 2020-12-10 11:39
adding 
![image](https://user-images.githubusercontent.com/43988371/101767566-61b69700-3b0a-11eb-9656-474dffbedcf7.png)

resolves the problem I think

this gives the result like this
![image](https://user-images.githubusercontent.com/43988371/101767598-6ed38600-3b0a-11eb-83c0-7f116b3f24b2.png)

**Comment by lex111** [comment] 2020-12-10 11:44
> Maybe for <th>, <td> we can remove this background color? @lex111 any opinions here?

Should be fixed in #1729

> Not only <th><tr> we have do it for <ul> and <li> as the side navigation also have the same issue

Does this really need to be fixed? It seemed to me the expected behavior (like in other sites).

**Comment by bazzadp** [comment] 2020-12-10 11:49
Yeah I think I've with leaving the style in `<ul>` and `<li>`:

![CSS chapter ToC](https://user-images.githubusercontent.com/10931297/101768573-a4ae4580-3add-11eb-9cf6-138a186ba1ed.png)

Maybe not as obvious on the `all` but here's the caching chapter:

![Caching ToC](https://user-images.githubusercontent.com/10931297/101768633-bee82380-3add-11eb-9c3d-2dfe1fbf1414.png)

**Closed** 2020-12-10 12:21 UTC
Labels: bug, development
