### ISSUE TITLE
Table of Contents dropdown list

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#985] opened 2020-07-08 18:04 UTC
I often find myself wanting to jump to a specific chapter. There are a few ways to do this currently:

- navigate via direct URL
- navigate to the TOC page and click the link
- move sequentially previous/next from chapter to chapter

I'd like to propose a new UI that works from any page to navigate directly to any given chapter. The "Table of Contents" link in the header could reveal a dropdown list of chapters on hover/focus. See the "Reports" list on the HTTP Archive website, for example:

![image](https://user-images.githubusercontent.com/1120896/86953921-24954580-c123-11ea-9ecb-a61049deb50f.png)

The contents of the list would be the chapters in order and grouped by section, as they appear on the TOC page. These chapters should be generated by the config and not hardcoded, to make it applicable for any year. It must also be fully accessible and follow best practices.

Some design work is needed. The list of chapters is long so we would need to design it with scrolling in mind. And we may want a mobile-specific design or, for example, rely on native UI for radio inputs.

Any @HTTPArchive/developers interested in building this?

**Comment by MSakamaki** [comment] 2020-10-29 02:00
I want to get to work on this.
I'll try to fix the table of contents to a dropdown list first.

**Comment by rviscomi** [comment] 2020-10-29 02:06
Great, thanks @MSakamaki! See #986 for the related style changes.

**Comment by MSakamaki** [comment] 2020-10-30 02:48
@rviscomi 
I implemented the dropdown as advised.
some refactoring and will submit a PR today.

PC Header
![pc-header](https://user-images.githubusercontent.com/2183053/97654112-9a903480-1aa5-11eb-96b2-8db14ea1e818.png)

PC Footer
![pc-footer](https://user-images.githubusercontent.com/2183053/97654120-9ebc5200-1aa5-11eb-817d-450a4d44de54.png)

Mobile Header
![mobile-header](https://user-images.githubusercontent.com/2183053/97654130-a1b74280-1aa5-11eb-9de9-0a013ddd4b02.png)

Mobile Header (select)
![mobile-header-select](https://user-images.githubusercontent.com/2183053/97654135-a4b23300-1aa5-11eb-9b76-796c5f7d8e5d.png)

Mobile Footer
![mobile-footer](https://user-images.githubusercontent.com/2183053/97654146-a7ad2380-1aa5-11eb-8e5a-214a5d56caed.png)

**Comment by bazzadp** [comment] 2020-11-12 13:07
Fixed in #1393

**Comment by rviscomi** [comment] 2020-11-14 17:04
Thank you @MSakamaki I love this new dropdown! Reopening to track a couple of small nits I noticed while playing with the dropdown.

1. Should the dropdown icon animate to a checkmark? This made sense for the year/lang pickers because it always reflected the current selection. But with the TOC dropdown, "Table of Contents" is always the button text, not the current selection.

![image](https://user-images.githubusercontent.com/1120896/99152566-8b49e300-2670-11eb-8568-3879cb17a8f0.png)

2. Should the current chapter's style be muted? There may need to be better differentiation between a chapter that hasn't launched yet and is not clickable and the currently selected chapter, which is clickable. Not sure how good it would look but one idea is to make all clickable links underlined. Live chapters should all be white. So if I'm on the Markup page, it's white but not underlined or clickable. The Capabilities chapter would be both white and clickable. An unlaunched chapter like CSS would be muted and not underlined nor clickable.

![image](https://user-images.githubusercontent.com/1120896/99152636-f5fb1e80-2670-11eb-9443-f2c8408d4ea2.png)

**Comment by bazzadp** [comment] 2020-11-14 17:14
1. what about animate from down arrow to up arrow (^) instead of tick? I can include this in #1512 

2. Not so sure about this. This is a very short term thing until other chapters are launched (hopefully next release but probably still some stragglers realistically) and I think the underlines are a bit ugly. Ultimately they are both not clickable.

**Comment by bazzadp** [comment] 2020-11-14 17:45
Could also add a tick next to the current chapter. That would be consistent with year and language.

**Comment by rviscomi** [comment] 2020-11-14 18:19
> Could also add a tick next to the current chapter. That would be consistent with year and language, and what native select element shows on mobile.

Yeah I like that idea. Rather than the TOC text having the checkmark, denote the current chapter/page. Yellow + check?

> Not so sure about this. This is a very short term thing until other chapters are launched (hopefully next release but probably still some stragglers realistically) and I think the underlines are a bit ugly. Ultimately they are both not clickable.

Current chapter is still clickable, but styled like ones that aren't, which is what threw me off. Clarified my previous comment to suggest that we should make the style more prominent for current chapters, which I think is also solved by your idea.

**Comment by bazzadp** [comment] 2020-11-14 18:26
The current chapter shouldn’t be clickable at all. That’s a bug. We used to have this in place but looks like we lost it when @MSakamaki refactored code a little to stop having lists of lists (necessary to make up/down keys work). We should fix that.

Quick look at the code on my phone shows it works as intended for non-chapters but not for the chapters.

Agree with the rest. Will look to see what’s easy to add to #1512

**Comment by bazzadp** [comment] 2020-11-14 19:47
Have a play with the `toc_dropdown_invalid_html` branch.

Existing chapter 2019:

![2019 menu](https://user-images.githubusercontent.com/10931297/99155671-ee0f9e80-26b1-11eb-811b-c33128ab932b.png)

Existing chapter 2020:

![2020 menu](https://user-images.githubusercontent.com/10931297/99155709-4181ec80-26b2-11eb-8647-07b4eee02e7e.png)

**Closed** 2020-11-22 10:37 UTC
Labels: design, development, good first issue
