### ISSUE TITLE
SEO and Graph Elements

### ISSUE THREAD

**Issue by merlinox** [HTTPArchive/almanac.httparchive.org#461] opened 2019-11-11 14:57 UTC
Hi, in this interesting page the <graph> elements don't work:
almanac.httparchive.org/en/2019/seo

Thanks

**Comment by bazzadp** [comment] 2019-11-11 15:00
Hi @merlinox , some of the chapters (including this one) are still being edited for typos and to add the graphics. This is why they have [UNEDITED] at the top of those few chapters that still need this done.

**Comment by merlinox** [comment] 2019-11-11 15:01
Thank you so much and sorry for my hit.
———————————————————————————————————
Riccardo Mares *aka *Merlinox
> Blog <http://blog.merlinox.com/> - EnduMag
<https://mag.endu.net/author/riccardo-mares/> - Linkedin
<https://www.linkedin.com/in/merlinox> - Instagram
<https://www.instagram.com/merlinox/> - Twitter
<https://twitter.com/merlinox> - Facebook
<https://www.facebook.com/merlinox> <

**Comment by rviscomi** [comment] 2019-11-11 17:12
Duplicate of #237

**Closed by rviscomi** 2019-11-11 17:12 UTC
Labels: Writing, bug
