### ISSUE TITLE
Query metrics update: Chapter 17. CDN

### ISSUE THREAD

**Issue by colinbendell** [HTTPArchive/almanac.httparchive.org#206] opened 2019-10-16 17:32 UTC
After some data exploration, the CDN metrics need to be refined. Specifically the distinction between firstHtml, same domain, and third party hosting, the frequency count should be based on request/hits and not on hosts, tls negotiation timing should consider resumed vs first request and many other conditions

**Comment by rviscomi** [comment] 2019-10-16 20:58
I think this is a duplicate of #98 which I reopened

**Closed** 2019-10-16 20:59 UTC
